### ISSUE TITLE
Does not work using Phoenix 1.1

### ISSUE THREAD

**Issue by thestonefox** [slashdotdash/phoenix-react-redux-example#6]
When trying to install and run you get a javascript console error "js/app.js not found"

This is due to a conflict in Phoenix and Babel 6

(see here for the fix to that conflict -> https://github.com/matthewlehner/phoenix/commit/8f6a9eb57dbb89a028e64ed160c08d42425efdd7)

So you need to manually patch your "deps/phoenix/web/static/js/phoenix.js" and `mix deps.compile` to get it work.

Also... The instructions of use in your readme don't mention this, but shouldn't you also have to run `webpack` otherwise how does the js get built into the phoenix app?

**Comment by thestonefox** [comment]
i see this has already been mentioned

**Comment by slashdotdash** [comment]
You're right that I did have to manually apply the change to the `phoenix.js` file as you linked. I then forgot I had made the change when I documented the steps. 

I need to take a look at upgrading this example to Phoenix 1.1 because the code has been changed. Hopefully it now compiles with Babel.
